/**
 * MeterReadings Model with Schema Definition
 * 
 * Auto-generated from database schema
 * Single source of truth for MeterReadings entity
 */

const BaseModel = require('../../../../framework/backend/api/base/BaseModel');
const { defineSchema, field, relationship, FieldTypes, RelationshipTypes } = require('../../../../framework/backend/api/base/SchemaDefinition');

class MeterReadings extends BaseModel {
    constructor(data = {}) {
        super(data);
        
        // Auto-initialize all fields from schema
        MeterReadings.schema.initializeFromData(this, data);
    }
    
    static get tableName() {
        return 'meter_readings';
    }
    
    static get primaryKey() {
        return 'id';
    }

    // ===== SCHEMA DEFINITION (Single Source of Truth) =====
    
    static get schema() {
        return defineSchema({
            entityName: 'MeterReadings',
            tableName: 'meter_readings',
            description: 'MeterReadings entity',
            
            // Form fields - user can edit these
            formFields: {
                source: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Source',
                    dbField: 'source',
                    maxLength: 100,
                }),
                quality: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Quality',
                    dbField: 'quality',
                    maxLength: 20,
                }),
                voltage: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Voltage',
                    dbField: 'voltage',
                }),
                current: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Current',
                    dbField: 'current',
                }),
                power: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Power',
                    dbField: 'power',
                }),
                energy: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Energy',
                    dbField: 'energy',
                }),
                frequency: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Frequency',
                    dbField: 'frequency',
                }),
                powerfactor: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Powerfactor',
                    dbField: 'powerfactor',
                }),
                temperature: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Temperature',
                    dbField: 'temperature',
                }),
                kwh: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Kwh',
                    dbField: 'kwh',
                }),
                kw: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Kw',
                    dbField: 'kw',
                }),
                v: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'V',
                    dbField: 'v',
                }),
                a: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'A',
                    dbField: 'a',
                }),
                dpf: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Dpf',
                    dbField: 'dpf',
                }),
                dpfchannel: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Dpfchannel',
                    dbField: 'dpfchannel',
                }),
                kwpeak: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Kwpeak',
                    dbField: 'kwpeak',
                }),
                kvarh: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Kvarh',
                    dbField: 'kvarh',
                }),
                kvah: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Kvah',
                    dbField: 'kvah',
                }),
                phaseavoltage: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phaseavoltage',
                    dbField: 'phaseavoltage',
                }),
                phasebvoltage: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phasebvoltage',
                    dbField: 'phasebvoltage',
                }),
                phasecvoltage: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phasecvoltage',
                    dbField: 'phasecvoltage',
                }),
                phaseacurrent: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phaseacurrent',
                    dbField: 'phaseacurrent',
                }),
                phasebcurrent: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phasebcurrent',
                    dbField: 'phasebcurrent',
                }),
                phaseccurrent: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phaseccurrent',
                    dbField: 'phaseccurrent',
                }),
                phaseapower: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phaseapower',
                    dbField: 'phaseapower',
                }),
                phasebpower: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phasebpower',
                    dbField: 'phasebpower',
                }),
                phasecpower: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Phasecpower',
                    dbField: 'phasecpower',
                }),
                deviceIp: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Device Ip',
                    dbField: 'device_ip',
                    maxLength: 50,
                }),
                port: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Port',
                    dbField: 'port',
                }),
                slaveId: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Slave Id',
                    dbField: 'slave_id',
                }),
                powerFactor: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Power Factor',
                    dbField: 'power_factor',
                }),
                phaseAVoltage: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase A Voltage',
                    dbField: 'phase_a_voltage',
                }),
                phaseBVoltage: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase B Voltage',
                    dbField: 'phase_b_voltage',
                }),
                phaseCVoltage: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase C Voltage',
                    dbField: 'phase_c_voltage',
                }),
                phaseACurrent: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase A Current',
                    dbField: 'phase_a_current',
                }),
                phaseBCurrent: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase B Current',
                    dbField: 'phase_b_current',
                }),
                phaseCCurrent: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase C Current',
                    dbField: 'phase_c_current',
                }),
                phaseAPower: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase A Power',
                    dbField: 'phase_a_power',
                }),
                phaseBPower: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase B Power',
                    dbField: 'phase_b_power',
                }),
                phaseCPower: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase C Power',
                    dbField: 'phase_c_power',
                }),
                lineToLineVoltageAb: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Line To Line Voltage Ab',
                    dbField: 'line_to_line_voltage_ab',
                }),
                lineToLineVoltageBc: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Line To Line Voltage Bc',
                    dbField: 'line_to_line_voltage_bc',
                }),
                lineToLineVoltageCa: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Line To Line Voltage Ca',
                    dbField: 'line_to_line_voltage_ca',
                }),
                totalActivePower: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Total Active Power',
                    dbField: 'total_active_power',
                }),
                totalReactivePower: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Total Reactive Power',
                    dbField: 'total_reactive_power',
                }),
                totalApparentPower: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Total Apparent Power',
                    dbField: 'total_apparent_power',
                }),
                totalActiveEnergyWh: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Total Active Energy Wh',
                    dbField: 'total_active_energy_wh',
                }),
                totalReactiveEnergyVarh: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Total Reactive Energy Varh',
                    dbField: 'total_reactive_energy_varh',
                }),
                totalApparentEnergyVah: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Total Apparent Energy Vah',
                    dbField: 'total_apparent_energy_vah',
                }),
                frequencyHz: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Frequency Hz',
                    dbField: 'frequency_hz',
                }),
                temperatureC: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Temperature C',
                    dbField: 'temperature_c',
                }),
                humidity: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Humidity',
                    dbField: 'humidity',
                }),
                neutralCurrent: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Neutral Current',
                    dbField: 'neutral_current',
                }),
                phaseAPowerFactor: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase A Power Factor',
                    dbField: 'phase_a_power_factor',
                }),
                phaseBPowerFactor: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase B Power Factor',
                    dbField: 'phase_b_power_factor',
                }),
                phaseCPowerFactor: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase C Power Factor',
                    dbField: 'phase_c_power_factor',
                }),
                voltageThd: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Thd',
                    dbField: 'voltage_thd',
                }),
                currentThd: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Thd',
                    dbField: 'current_thd',
                }),
                maxDemandKw: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Max Demand Kw',
                    dbField: 'max_demand_kw',
                }),
                maxDemandKvar: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Max Demand Kvar',
                    dbField: 'max_demand_kvar',
                }),
                maxDemandKva: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Max Demand Kva',
                    dbField: 'max_demand_kva',
                }),
                voltageUnbalance: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Unbalance',
                    dbField: 'voltage_unbalance',
                }),
                currentUnbalance: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Unbalance',
                    dbField: 'current_unbalance',
                }),
                communicationStatus: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Communication Status',
                    dbField: 'communication_status',
                    maxLength: 20,
                }),
                deviceModel: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Device Model',
                    dbField: 'device_model',
                    maxLength: 100,
                }),
                firmwareVersion: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Firmware Version',
                    dbField: 'firmware_version',
                    maxLength: 100,
                }),
                serialNumber: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Serial Number',
                    dbField: 'serial_number',
                    maxLength: 100,
                }),
                alarmStatus: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Alarm Status',
                    dbField: 'alarm_status',
                    maxLength: 20,
                }),
                dataQuality: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Data Quality',
                    dbField: 'data_quality',
                    maxLength: 20,
                }),
                rawBasic: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Raw Basic',
                    dbField: 'raw_basic',
                }),
                rawExtended: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Raw Extended',
                    dbField: 'raw_extended',
                }),
                importActiveEnergyWh: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Import Active Energy Wh',
                    dbField: 'import_active_energy_wh',
                }),
                exportActiveEnergyWh: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Export Active Energy Wh',
                    dbField: 'export_active_energy_wh',
                }),
                importReactiveEnergyVarh: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Import Reactive Energy Varh',
                    dbField: 'import_reactive_energy_varh',
                }),
                exportReactiveEnergyVarh: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Export Reactive Energy Varh',
                    dbField: 'export_reactive_energy_varh',
                }),
                groundCurrent: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Ground Current',
                    dbField: 'ground_current',
                }),
                voltageThdPhaseA: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Thd Phase A',
                    dbField: 'voltage_thd_phase_a',
                }),
                voltageThdPhaseB: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Thd Phase B',
                    dbField: 'voltage_thd_phase_b',
                }),
                voltageThdPhaseC: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Thd Phase C',
                    dbField: 'voltage_thd_phase_c',
                }),
                currentThdPhaseA: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Thd Phase A',
                    dbField: 'current_thd_phase_a',
                }),
                currentThdPhaseB: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Thd Phase B',
                    dbField: 'current_thd_phase_b',
                }),
                currentThdPhaseC: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Thd Phase C',
                    dbField: 'current_thd_phase_c',
                }),
                voltageHarmonic_3: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Harmonic 3',
                    dbField: 'voltage_harmonic_3',
                }),
                voltageHarmonic_5: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Harmonic 5',
                    dbField: 'voltage_harmonic_5',
                }),
                voltageHarmonic_7: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Harmonic 7',
                    dbField: 'voltage_harmonic_7',
                }),
                currentHarmonic_3: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Harmonic 3',
                    dbField: 'current_harmonic_3',
                }),
                currentHarmonic_5: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Harmonic 5',
                    dbField: 'current_harmonic_5',
                }),
                currentHarmonic_7: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Harmonic 7',
                    dbField: 'current_harmonic_7',
                }),
                currentDemandKw: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Demand Kw',
                    dbField: 'current_demand_kw',
                }),
                currentDemandKvar: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Demand Kvar',
                    dbField: 'current_demand_kvar',
                }),
                currentDemandKva: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Demand Kva',
                    dbField: 'current_demand_kva',
                }),
                predictedDemandKw: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Predicted Demand Kw',
                    dbField: 'predicted_demand_kw',
                }),
                voltageFlicker: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Flicker',
                    dbField: 'voltage_flicker',
                }),
                frequencyDeviation: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Frequency Deviation',
                    dbField: 'frequency_deviation',
                }),
                phaseSequence: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase Sequence',
                    dbField: 'phase_sequence',
                    maxLength: 10,
                }),
                phaseRotation: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Phase Rotation',
                    dbField: 'phase_rotation',
                    maxLength: 10,
                }),
                powerDirection: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Power Direction',
                    dbField: 'power_direction',
                    maxLength: 10,
                }),
                reactiveDirection: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Reactive Direction',
                    dbField: 'reactive_direction',
                    maxLength: 12,
                }),
                lastCommunication: field({
                    type: FieldTypes.DATE,
                    default: '',
                    required: false,
                    label: 'Last Communication',
                    dbField: 'last_communication',
                }),
                manufacturerCode: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Manufacturer Code',
                    dbField: 'manufacturer_code',
                }),
                deviceTime: field({
                    type: FieldTypes.DATE,
                    default: '',
                    required: false,
                    label: 'Device Time',
                    dbField: 'device_time',
                }),
                syncStatus: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Sync Status',
                    dbField: 'sync_status',
                    maxLength: 20,
                }),
                timeSource: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Time Source',
                    dbField: 'time_source',
                    maxLength: 20,
                }),
                eventCounter: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Event Counter',
                    dbField: 'event_counter',
                }),
                lastEvent: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Last Event',
                    dbField: 'last_event',
                }),
                currentTransformerRatio: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Current Transformer Ratio',
                    dbField: 'current_transformer_ratio',
                }),
                voltageTransformerRatio: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Voltage Transformer Ratio',
                    dbField: 'voltage_transformer_ratio',
                }),
                pulseConstant: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Pulse Constant',
                    dbField: 'pulse_constant',
                }),
                modbusRegister_40001: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Modbus Register 40001',
                    dbField: 'modbus_register_40001',
                }),
                modbusRegister_40002: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Modbus Register 40002',
                    dbField: 'modbus_register_40002',
                }),
                modbusRegister_40003: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Modbus Register 40003',
                    dbField: 'modbus_register_40003',
                }),
                modbusRegister_40004: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Modbus Register 40004',
                    dbField: 'modbus_register_40004',
                }),
                modbusRegister_40005: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Modbus Register 40005',
                    dbField: 'modbus_register_40005',
                }),
                status: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Status',
                    dbField: 'status',
                    maxLength: 20,
                }),
                unitOfMeasurement: field({
                    type: FieldTypes.STRING,
                    default: '',
                    required: false,
                    label: 'Unit Of Measurement',
                    dbField: 'unit_of_measurement',
                    maxLength: 20,
                }),
                meterId: field({
                    type: FieldTypes.NUMBER,
                    default: 0,
                    required: false,
                    label: 'Meter Id',
                    dbField: 'meter_id',
                })
            },
            
            // Entity fields - read-only, system-managed
            entityFields: {
                id: field({
                    type: FieldTypes.STRING,
                    default: null,
                    readOnly: true,
                    label: 'Id',
                    dbField: 'id',
                }),
                createdat: field({
                    type: FieldTypes.DATE,
                    default: null,
                    readOnly: true,
                    label: 'Createdat',
                    dbField: 'createdat',
                }),
                tenantId: field({
                    type: FieldTypes.NUMBER,
                    default: null,
                    readOnly: true,
                    label: 'Tenant Id',
                    dbField: 'tenant_id',
                })
            },
            
            // Relationships
            relationships: {
                meter: relationship({
                    type: RelationshipTypes.BELONGS_TO,
                    model: 'Meter',
                    foreignKey: 'meter_id',
                    autoLoad: false,
                }),
            },
            
            validation: {},
        });
    }
}

module.exports = MeterReadings;
