// @ts-nocheck
/**
 * Meter Model for PostgreSQL
 * Extends BaseModel for automatic CRUD generation
 */

const BaseModel = require('../../../../framework/backend/api/base/BaseModel');
const db = require('../config/database');

class Meter extends BaseModel {
  constructor(meterData = {}) {
    super(meterData);
    
    // Field definitions only - CRUD methods are generated by BaseModel
    this.id = meterData.id;
    this.name = meterData.name;
    this.type = meterData.type;
    this.serial_number = meterData.serial_number;
    this.installation_date = meterData.installation_date;
    this.device_id = meterData.device_id;
    this.device_name = meterData.device_name;
    this.device_description = meterData.device_description;
    this.location_id = meterData.location_id;
    this.location_location = meterData.location_location;
    this.location_floor = meterData.location_floor;
    this.location_room = meterData.location_room;
    this.location_description = meterData.location_description;
    this.ip = meterData.ip;
    this.port = meterData.port;
    this.protocal = meterData.protocal;
    this.status = meterData.status || 'online';
    this.next_maintenance = meterData.next_maintenance;
    this.last_maintenance = meterData.last_maintenance;
    this.maintenance_interval = meterData.maintenance_interval;
    this.maintenance_notes = meterData.maintenance_notes;
    this.register_map = meterData.register_map; // JSONB column
    this.notes = meterData.notes;
    this.active = meterData.active;
    this.created_at = meterData.created_at;
    this.updated_at = meterData.updated_at;
  }

  // ===== Static Configuration =====
  
  /**
   * Database table name
   */
  static get tableName() {
    return 'meter';
  }

  /**
   * Primary key field
   */
  static get primaryKey() {
    return 'id';
  }

  /**
   * Relationship definitions
   */
  static get relationships() {
    return {
      device: {
        type: 'belongsTo',
        model: 'Device',
        foreignKey: 'device_id',
        targetKey: 'id'
      },
      location: {
        type: 'belongsTo',
        model: 'Location',
        foreignKey: 'location_id',
        targetKey: 'id'
      }
    };
  }

  // ===== Custom Methods =====

  /**
   * Find meter by meter ID (custom business logic)
   */
  static async findByMeterId(meterid) {
    return this.findOne({ meterid });
  }

  /**
   * Get meter statistics
   */
  static async getStats() {
    const query = `
      SELECT
        COUNT(*) as total_meters,
        COUNT(CASE WHEN status = 'active' THEN 1 END) as active_meters,
        COUNT(CASE WHEN status = 'inactive' THEN 1 END) as inactive_meters,
        COUNT(CASE WHEN type = 'electric' THEN 1 END) as electric_meters,
        COUNT(CASE WHEN type = 'gas' THEN 1 END) as gas_meters,
        COUNT(CASE WHEN type = 'water' THEN 1 END) as water_meters,
        COUNT(DISTINCT location_location) as locations_with_meters
      FROM meter
    `;

    const result = await db.query(query);
    return result.rows[0];
  }

  /**
   * Get full location string
   */
  get fullLocation() {
    const parts = [
      this.location_location,
      this.location_floor && `Floor ${this.location_floor}`,
      this.location_room && `Room ${this.location_room}`,
      this.location_description
    ].filter(part => part && part.trim());
    
    return parts.join(', ');
  }

  /**
   * Convert to JSON
   */
  toJSON() {
    return {
      ...this,
      fullLocation: this.fullLocation
    };
  }
}

module.exports = Meter;
